name: Test, compile and push client and server to production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  client-tests:
    uses: WildCodeSchool/2023-11-wns-bleu-g2-christmas-gifts-planner/.github/workflows/test-front.yml@main

  e2e-tests:
    uses: WildCodeSchool/2023-11-wns-bleu-g2-christmas-gifts-planner/.github/workflows/e2e-tests.yml@main

  integration-tests:
    uses: WildCodeSchool/2023-11-wns-bleu-g2-christmas-gifts-planner/.github/workflows/integration-tests.yml@main

  build-and-push-server:
    needs:
      - integration-tests
      - e2e-tests
    uses: WildCodeSchool/2023-11-wns-bleu-g2-christmas-gifts-planner/.github/workflows/build-backend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: docky1921/Gifty-back

  build-and-push-client:
    needs:
      - client-tests
      - e2e-tests
    uses: WildCodeSchool/2023-11-wns-bleu-g2-christmas-gifts-planner/.github/workflows/build-frontend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: docky1921/Gifty-front

  notify-vps:
    needs:
      - build-and-push-client
      - build-and-push-server
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update production
        uses: wei/curl@master
        with:
          args: https://ops.1123-bleu-2.wns.wilders.dev/hooks/update-production
